<!-- Header File Include -->
<?php $activePage = 'solutions'; include "header.php"; ?>

<!-- Aws Page -->
<section id="career-banner">
    <div class="container-fluid">
        <div class="row">
            <div class="text-center">
                <div class="career-container career-b-clr">
                    <img src="img/blockch.jpg" alt="banner-img" class="career-img img-fluid"/>
                        <div class="overlay-career">
                        <div class="career-text mt-4">
                            <h2>Block Chain</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section id="dw-ctnt" class="my-5">
    <div class="container text-justify">
        <div class="row mb-1">
            <div class="col-md-8 col-xs-12 mt-2 mb-5">
                <h2 class="mb-4">Block Chain</h2>
                <p> 
                    A blockchain is a digital record of transactions. The name comes from its structure, in which 
                    individual records, called blocks, are linked together in single list, called a chain. Blockchains
                    are used for recording transactions made with cryptocurrencies, such as Bitcoin, and have many 
                    other applications.
                </p>
                <!-- <p></p> -->
                 <ul class="fa-ul">
                    <li><i class="fa-li fa fa-cog fa-lg"></i>A blockchain is a growing list of records, called blocks, which are linked using cryptography. </li>
                    <li><i class="fa-li fa fa-cog fa-lg"></i>Each block contains a cryptographic hash of the previous block, a timestamp, and transaction data. By design, a blockchain is resistant to modification of the data</li>
                    <li><i class="fa-li fa fa-cog fa-lg"></i>Blockchain was invented by Satoshi Nakamoto in 2008 to serve as the public transaction ledger of the cryptocurrency bitcoin</li>
                    <li><i class="fa-li fa fa-cog fa-lg"></i>The invention of the blockchain for bitcoin made it the first digital currency to solve the double-spending problem without the need of a trusted authority or central server.</li>
                    <li><i class="fa-li fa fa-cog fa-lg"></i>Blockchain is considered a type of payment rail. Private blockchains have been proposed for business use. </li>
                </ul>
            </div>
            <div class="col-md-4 col-xs-12  ">
                <img src="img/blockchain.png" alt="" class="img-fluid">
            </div>
            <br>
            <br>
            <div class="col-md-12 col-xs-12  ">
                <p style="font-weight:500;">Ethereum</p>
                <ul class="fa-ul">
                    <li><i class="fa-li fa fa-cog fa-lg"></i> Ethereum is an open-source, public, blockchain-based distributed computing platform and operating system featuring smart contract (scripting) functionality. It supports a modified version of Nakamoto consensus via transaction-based state transitions. </li>
                </ul>
                
            </div>
            <div class="col-md-12 col-xs-12  ">
                <p style="font-weight:500;">Smart Contract</p>
                <ul class="fa-ul">
                    <li><i class="fa-li fa fa-cog fa-lg"></i> A smart contract is a computer protocol intended to digitally facilitate, verify, or enforce the negotiation or performance of a contract. Smart contracts allow the performance of credible transactions without third parties. These transactions are trackable and irreversible. </li>
                </ul>
            </div>
            <div class="col-md-12 col-xs-12  ">
                <p style="font-weight:500;">NEO </p>
                <ul class="fa-ul">
                    <li><i class="fa-li fa fa-cog fa-lg"></i> A NEO is a blockchain platform and cryptocurrency designed to build a scalable network of decentralized applications. The base asset of the NEO blockchain is the non divisible NEO token which generates GAS tokens that can be used to pay for transaction fees generated by applications on the network. </li>
                </ul>
                <br>
            </div>
           
        </div>
    </div>
</section>
<!-- Footer File Incude -->
<?php include "footer.php"; ?>